### PR TITLE
Dbatiste/consistent script names

### PR DESCRIPTION
**Pull request by dbatiste**

### CODE REVIEW

**Comment by svanherk** [comment]
This still might have a problem, I think the script always expects a polymer lint and a eslint

**Comment by dbatiste** [comment]
Yeah, correcting that now.  I am sorta torn about adding the eslint dependency to hybrid but there isn't any harm so I am in the process of doing that.  The assumption that these will be present is _probably_ valid almost all the time.

**Comment by dbatiste** [comment]
Might be worth adding something to the readme about the naming of these since cleanup will definitely be required for a few repos.

**Comment by svanherk** [comment]
The README for the `polymer-3-converter`?  Yup I can do that! Speaking of, should I add instructions about what we want to do to the readmes as we go along?  And what is that?  I'm thinking:
1) Say that the component is Polymer 3
2) Update how to use it
3) Mention hybrid branch?

**Pull request merged**
