### PR TITLE
Experiment: Saucify Galen

### PR DESCRIPTION
**Pull request by awikkerink**

### CODE REVIEW

**Comment by dlockhart** [comment]
@awikkerink how stale do you think this is? I was thinking of reviving it and getting it merged in as I'm making some typography changes. Am I doomed?

**Comment by awikkerink** [comment]
It is kinda stale. I wrote a d2l-galen-util package in the meantime as
well. It may be better to grab the .Gspec files and redo this

**Comment by awikkerink** [comment]
Actually, this one should still be okay. I rebased, so let's see if things still work

**Comment by awikkerink** [comment]
The reports aren't collected, but this can be done in another PR.

**Comment by awikkerink** [comment]
Uh-Oh
```
node_modules/.bin/sc-run [options] [--] [<test command>]
[galen] 
[galen] You must provide your Sauce Labs username and access key, either as
[galen] options or as environment variables (see below).
```

**Comment by awikkerink** [comment]
@dlockhart Good to go?

**Pull request merged**
